# Generated by Django 4.2.7 on 2026-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_campaign_affected_products_campaignproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_pixel_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
