# Generated by Django 4.2.7 on 2026-01-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('gateway', 'Gateway'), ('cod', 'COD')], default='manual', max_length=20)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_logos/')),
            ],
        ),
    ]
