# Generated by Django 4.2.7 on 2026-01-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Called - No Answer', 'Called - No Answer'), ('Called - Successful', 'Called - Successful'), ('Not Interested', 'Not Interested'), ('Follow Later', 'Follow Later')], default='Pending', max_length=50)),
                ('rating', models.IntegerField(default=0, help_text='Customer satisfaction rating 1-5')),
                ('notes', models.TextField(blank=True)),
                ('is_interested_in_new_products', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_followups', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='orders.order')),
            ],
        ),
    ]
