# Generated by Django 4.2.7 on 2026-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('inside_dhaka_shipping', models.DecimalField(decimal_places=2, default=60.0, max_digits=10)),
                ('outside_dhaka_shipping', models.DecimalField(decimal_places=2, default=120.0, max_digits=10)),
            ],
        ),
    ]
