# Generated by Django 4.2.7 on 2026-01-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='followup_type',
            field=models.CharField(choices=[('Post-Purchase', 'Post-Purchase'), ('Recurring', 'Recurring'), ('Win-back', 'Win-back'), ('Other', 'Other')], default='Post-Purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='orders.order'),
        ),
    ]
