# Generated by Django 6.0 on 2025-12-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_data', models.TextField(blank=True, help_text='Base64 Data URI from frontend', null=True)),
                ('link', models.CharField(default='/shop', max_length=255)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('position', models.CharField(choices=[('hero', 'Hero Slider'), ('grid-1', 'Grid Slot 1'), ('grid-2', 'Grid Slot 2'), ('grid-3', 'Grid Slot 3'), ('grid-4', 'Grid Slot 4')], default='hero', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('button_color', models.CharField(default='#000000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Shipping', 'Shipping'), ('Payment', 'Payment'), ('Returns', 'Returns')], default='General', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='HTML Content')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
