# Generated by Django 4.2.7 on 2026-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_themeconfig_alter_banner_id_alter_faq_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_data',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.TextField(help_text='Image URL'),
        ),
    ]
