# Generated by Django 4.2.7 on 2026-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_banner_image_data_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
