# Generated by Django 4.2.7 on 2026-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_banner_button_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='http://bulksmsbd.net/api/smsapi', max_length=255)),
                ('api_key', models.CharField(default='', max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_template', models.TextField(default='Your OTP is {otp}')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
