# Generated by Django 4.2.7 on 2025-12-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_seo_description_product_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(default=True),
        ),
    ]
