# Generated by Django 4.2.7 on 2025-12-30 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_allow_backorders_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='combinations',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_combinations', to='store.product')),
            ],
        ),
    ]
