# Generated by Django 4.2.7 on 2025-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
