# Generated by Django 4.2.7 on 2025-12-30 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_purchaseorder_supplier_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
