# Generated by Django 4.2.7 on 2026-01-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_purchaseorder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='supplier_name',
        ),
    ]
