# Generated by Django 4.2.7 on 2026-01-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
