# Generated by Django 4.2.7 on 2026-01-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
